version: 2.1
jobs:
  start:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_project.sh”
workflows:
  build:
    jobs:
      - start
    
